### ISSUE TITLE
Fix the bot!

### ISSUE THREAD

**Issue by n0toose** [alwayslivid/TinyFlowerBeds#19]
So, I recently, carelessly merged #17 into the source of my Twitter bot, [TinyFlowerBeds](https://twitter.com/tinyflowerbeds). Something went completely wrong with `configparser`, however.

Here's what you'll need to do!
- Get the bot to read from a configuration file!
- Prove (with a screenshot or a log) that the bot can now parse the credentials properly!

**Comment by n0toose** [comment]
Hey, mind responding here so that I can assign this issue to you? @Oxigen96

**Comment by oxi-git** [comment]
Sure, here you go!

**Comment by n0toose** [comment]
Issue's all yours now! See you on pumpkin month! @Oxigen96
