### ISSUE TITLE
Create a GitHub Actions workflow that deploys new commits to Heroku!

### ISSUE THREAD

**Issue by n0toose** [alwayslivid/TinyFlowerBeds#21]
[**GitHub Actions**](https://github.com/features/actions) are pretty nifty as far as avoiding mundane tasks is concerned. Here's one for instance-- I normally deploy new versions of the bot by myself, manually, on [Heroku](https://heroku.com), which is where the bot is being hosted.

There's an action called [Deploy to Heroku](https://github.com/marketplace/actions/deploy-to-heroku) in the GitHub Marketplace. Use that and have your workflow push new revisions of the bot to Heroku immediately.

Use `${{secrets.X}}` variables for the application data related to Heroku-- I'll fill out the variables by myself. :D

**Comment by rohan2734** [comment]
hi i would like to work on this issue, I  want to work on github actions, can you provide some link, so that i could refer and do the task.

**Comment by n0toose** [comment]
> hi i would like to work on this issue, I want to work on github actions, can you provide some link, so that i could refer and do the task.

I did provide a bunch of resources in my issue itself. You'd have to look for repositories that also use it and, additionally, make sure that you have followed the instructions I provided correctly.

**Comment by rohan2734** [comment]
ok i will check

**Comment by rohan2734** [comment]
**Here it says that  a procfile or dockerfile is needed, do you have one?**

![procfile-dockerfile](https://user-images.githubusercontent.com/58523134/94357192-3d731e80-00b4-11eb-8b27-b8a9ed292ace.JPG)

**and what is the start script for the app? , idk because i am good at js, i have never worked with python.**

![procfile-creation](https://user-images.githubusercontent.com/58523134/94357191-3c41f180-00b4-11eb-985d-39918614287c.JPG)

**Comment by n0toose** [comment]
> **Here it says that a procfile or dockerfile is needed, do you have one?**

I'd appreciate it if you could consult the [repository's Procfile](https://github.com/panos/TinyFlowerBeds/blob/main/Procfile). That's all you'll need, apart from creating the workflow itself.

**Comment by rohan2734** [comment]
@panos  ok thanks., i am working on it.
-what is your app name on heroku 
-what is your mail id? for which tou have used to deploy on heroku?

**Comment by n0toose** [comment]
> @panos ok thanks., i am working on it.
> -what is your app name on heroku
> -what is your mail id? for which tou have used to deploy on heroku?

Please use secret variables.

**Comment by rohan2734** [comment]
>Please use secret variables.

ok i have updated it and posted a pull request , please check.

**Comment by n0toose** [comment]
Resolved in #22.
