### ISSUE TITLE
Do not tweet if the minimum interval is bigger than the time since the latest tweet.

### ISSUE THREAD

**Issue by n0toose** [alwayslivid/TinyFlowerBeds#3]
* Make sure that #2 has been resolved. `minInterval` should now be in the configuration ([`config.py`](src/config.py)) file, and the randomization should take place in the [`bot.py`](src/bot.py) file.
* Fetch the latest tweet's date from Twitter using `tweepy` (Documentation: http://docs.tweepy.org/en/latest/).
* Check whether the time since the latest tweet is smaller than `minInterval`. If that's the case, then do not tweet.
* If the bot shouldn't tweet, then what should it do? Your call.
* Open a pull request!

Here's a drawing that may help with understanding what needs to be done better;
![image](https://user-images.githubusercontent.com/30193966/78985488-9a444200-7b31-11ea-9b41-5032fd946397.png)

**Comment by molyvius** [comment]
![](https://user-images.githubusercontent.com/51362523/78993995-c4a0fa00-7b47-11ea-9eee-9a967311e5b8.png) 
the first one's done although my pull requests/commits have left my fork a bit of a mess.
Not really sure how to fetch the date using tweepy but I'll keep looking I guess.

**Comment by kandasamyc** [comment]
Can I work on this?

**Comment by n0toose** [comment]
Sure @SamC302!

Be aware, however-- it's not October 1st yet, so if you're coming over here thanks to Hacktoberfest, you'd have to wait a bit. I'm assigning the issue to you, but I'll have to give 3 days for you to fix it (until October 4th). I'll extend that by up to 4 days if you feel like you need it.


I'll also have to merge an outstanding pull request for #19-- @Oxigen96's change is good to go, but we're also waiting for October 1st.

**Comment by kandasamyc** [comment]
Quick update, I think I've figured out how to do it, I'm working on getting a twitter developer account to test it

**Comment by n0toose** [comment]
Thank you! (I also completely forgot the update, please note that it may take a while until you get the account.)
