### ISSUE TITLE
Update intro screen

### ISSUE THREAD

**Issue by n0toose** [alwayslivid/TinyFlowerBeds#8]
I initially started [TinyFlowerBeds](https://twitter.com/tinyflowerbeds) in order to better understand Python's useful (and silly) applications and how to create apps that will interact with social media. After I took a simple approach for it, I made an intro screen that shows the name of the project, a copyright notice for [the project's license](LICENSE) and **also added my name with a copyright sign**.

https://github.com/AlwaysLivid/TinyFlowerBeds/blob/ad525983d4a143db1f34802e38ea2460c55bab4d/src/bot.py#L18

I essentially abandoned the project, but I've revived it, because I noticed that it's a simple fun thing to work on and that others could learn some useful stuff by fiddling around with it (just as I did). When I started working on it, however, I did not expect anybody else to improve the thing that I did. There has been some interest revolving around it and there have been people that have contributed their own source code! According to the [GNU General Public License v3](LICENSE), the rights to the source code that they wrote belongs to them. I'm not the only copyright holder anymore!

So, here's what should change;
* The year should be updated from `2018-2019` to `2018-2020`.
* Change my alias (`AlwaysLivid`) to something that includes my name, as well as the `contributors`, as well as a link that lists all of the people that have contributed to the bot on GitHub.
* Make sure that the alignment remains intact. Feel free to make changes all over the string in order to maintain that.

**Comment by WingNuts5198** [comment]
I would like this task

**Comment by fairka** [comment]
Can I have this project?

**Comment by n0toose** [comment]
> Can I have this project?

Sure, feel free to give it a shot.

**Comment by GobindB** [comment]
Hey there, I've been looking to get involved with open source code and I'm eager to get going on my first PR! I wanted to see if this issue was still open and if so I'd love to give it a shot :) Alternatively, if there are any other somewhat beginner-friendly issues I could give a hand with I would love to get involved!

**Comment by n0toose** [comment]
> 
> 
> Hey there, I've been looking to get involved with open source code and I'm eager to get going on my first PR! I wanted to see if this issue was still open and if so I'd love to give it a shot :) Alternatively, if there are any other somewhat beginner-friendly issues I could give a hand with I would love to get involved!

Still open! Welcome to the club!
